# Generated by Django 6.0.4 on 2026-05-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantmodel',
            old_name='user',
            new_name='usr',
        ),
    ]
