# Generated by Django 6.0.4 on 2026-05-04 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0003_alter_resultmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participent', to='quize.participantmodel'),
        ),
    ]
